Whd 1 create a booking
rightinyourwheelhouse/wheelhouse-dashboard pull request #6
Opened 2021-09-24 08:10 UTC by JaimySchatteman

2021-09-24 08:51 UTC, darenmalfait requested changes

2021-09-24 08:51 UTC, darenmalfait commented on apps/office-service/src/app/app.module.ts
> +          synchronize: true, // TODO turn off synchronization when going into production
Maybe it's an idea to make the option configurable through en env variable with the default option being false so this never gets into production.

2021-09-24 08:51 UTC, darenmalfait commented on apps/office-service/src/booking/dto/create-booking.dto.ts
> +   *   TODO Write a custom validator that checks if the date in the
Can we put these TODO's in stories?

2021-09-24 08:51 UTC, darenmalfait commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
Are Docker Secrets something that needs to be used for this? @rafael-mindreau

2021-09-24 09:00 UTC, JaimySchatteman commented on apps/office-service/src/app/app.module.ts
> +          synchronize: true, // TODO turn off synchronization when going into production
I'll add to the configuration file

2021-09-24 09:01 UTC, JaimySchatteman commented on apps/office-service/src/booking/dto/create-booking.dto.ts
> +   *   TODO Write a custom validator that checks if the date in the
On it!

2021-09-24 22:04 UTC, RoelGo commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
The docker compose file is just used for development. No security concerns  here.

2021-09-24 22:11 UTC, RoelGo approved these changes

2021-09-27 07:06 UTC, darenmalfait commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
this is code going into production. It's not nice to have dev code in production.

2021-09-27 09:19 UTC, rafael-mindreau commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
Normally you don't want to push credentials to Git and you want to keep those secrets in `.env` that you gitignore, or keep the secrets in a Vault. However, this case is an exception. This is for a developer to be able to easily run a postgres instance on their own machine. The credentials only make sense for your own machine. So no data can be stolen this way.

An alternative way to keep using Docker would be to supply a `docker run` command in the README that developers can use, but it's way easier to just throw out a `docker-compose up -d` to start developing right away. If your OCD is still triggered, you can put these credentials in `.env` and then you would refer to the environment variable like so:

```yml
environment:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
```

But then again, that's just for OCD's. For me you can do what you want here 😅

2021-09-27 09:47 UTC, darenmalfait commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
I think the README option is fine, because then you can also document to why the docker file exists in the first place.

2021-09-27 09:48 UTC, darenmalfait commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
Let's go for the environment option. Good practise for when it needs to be done like that.

2021-09-27 09:50 UTC, darenmalfait commented on docker-compose.yml
>        POSTGRES_PASSWORD: development
make sure to put some documentation around it in the README aswell.

2021-09-27 11:41 UTC, darenmalfait requested changes

2021-09-27 11:41 UTC, darenmalfait commented on apps/office-service/src/main.ts
> +  const app = await NestFactory.create(AppModule, { cors: true });
Wat doet cors: true precies? Zet dat alles open?

2021-09-27 11:41 UTC, darenmalfait commented on apps/office-service/src/main.ts
> +  const app = await NestFactory.create(AppModule, { cors: true });
Kunnen we een ticket aanmaken om dat achteraf dicht te timmeren?

2021-09-27 11:58 UTC, JaimySchatteman commented on apps/office-service/src/main.ts
> +  const app = await NestFactory.create(AppModule, { cors: true });
Yes laat dat volledig toe dan!

2021-09-27 11:58 UTC, JaimySchatteman commented on apps/office-service/src/main.ts
> +  const app = await NestFactory.create(AppModule, { cors: true });
Ik maakt het ticket aan

2021-09-27 12:22 UTC, darenmalfait approved these changes

2021-09-27 12:23 UTC, merged